version: 2.1
jobs:
    verify-library:
      environment: 
        USER: "CI"
        CHANNEL: "prod"
      docker:
          - image: conanio/gcc6
      steps:
      - checkout     
      - run:
          name: pack python folder
          command: |
              cd parse-lib
              conan create . $USER/$CHANNEL --test-folder ../lib-test/
  
    master-integration:
      docker:
          - image: cimg/base:2020.01
      steps:
        - checkout 
        - add_ssh_keys:
            fingerprints:
              - "67:4a:d7:00:54:fd:88:cc:55:87:69:a7:8f:7f:90:6b"
        - run:
              name: Keyscan Github (HACK)
              command: |
                mkdir -p ~/.ssh
                ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        - run:
            name: merge with master
            command: |
                git fetch origin
                git checkout master
                git merge --ff-only $CIRCLE_BRANCH
                git push -u origin master
                git branch -d $CIRCLE_BRANCH
                git push origin --delete $CIRCLE_BRANCH

    deploy:
      docker:
          - image: conanio/gcc6
      steps:
          - checkout
          - run:  
              name: bump version
              command: |
                echo "deploy package to artifactory"
                echo "current version" && conan inspect . | grep 'version:'| awk '{print $2}'
      
workflows:
  version: 2
  build:
    jobs:
      - verify-library:
          filters:
            branches:
              only:
                - /ready\/.*/
      - master-integration:
          filters:
            branches:
              only:
                - /ready\/.*/
          requires:
            - verify-library
      - deploy:
          filters:
            branches:
              only:
                - /ready\/.*/
          requires:
            - master-integration