version: 2.1
jobs:
    verify-library:
      docker:
          - image: conanio/gcc6
      steps:
      - checkout
      - run:
          name: pack python folder
          command: |
              conan create . $USER/$CHANNEL --test-folder ../lib-test/
    
    master-integration:
      environment: 
          USER: "CI"
          CHANNEL: "prod"
      docker:
          - image: conanio/gcc6
      steps:
      - checkout
      - run:
          name: merge with master
          command: |
              git checkout -b master
              git merge --ff-only $CIRCLE_BRANCH
              git push -u origin master
              echo "deploy package to artifactory"

    increment-and-deploy:
      docker:
          - image: conanio/gcc6
      steps:
          - checkout
          - run:  
              name: bump version
              command: |
                cd parse-lib
                echo "current version" && conan inspect . | grep 'version:'| awk '{print $2}'
      
workflows:
  version: 2
  build:
    jobs:
      - verify-library:
          filters:
            branches:
              only:
                - /ready/.*
      - master-integration:
          filters:
            branches:
              only:
                - /ready/.*
          requires:
            - verify-library
      - increment-and-deploy:
          filters:
            branches:
              only:
                - master